package main

import (
	"fmt"
	//"time"
)

func main() {
	lg := createLeague(FB)
	com := createCommish("g", "dug")
	lg.AssignCommish(com)
	o, _ := createOwner("mr", "bigs", "tyty")
	o2, _ := createOwner("miut", "kgjfjg", "deezzz nuttsss")
	com.AddOwner(o)
	com.AddOwner(o2)
	o.SetSalary(500000.00)
	fmt.Println(o.AccountBalance)
	o.Pay()
	fmt.Println("just paid")
	fmt.Println(o.AccountBalance)
	o.Fine(7000)
	fmt.Println("just fined")
	fmt.Println(o.AccountBalance)

	// o.Fine(7000)
	// fmt.Printf("%2f\n last checj", o.AccountBalance)

	//com.ToggleElig()
	//fmt.Println(o.Eligible.LMActive)
	//com.ToggleElig()
	com.Suspend(o, 30, "owner-test")
	o.CheckSuspension()
	o.MediaPost("none", "owners rule!!!!", true)
	fmt.Println(o.Team.MessBoard)
	com.CheckSuspension()
	fmt.Println(o.GetName())
	com.SetSalary(40000.00)
	com.Pay()
	fmt.Println("-----------", o.Eligible.Slips[0])
	com.Fine(0)
	//fmt.Println(com.AccountBalance)
	pl := createPlayer("l", "b", WR)
	p2 := createPlayer("mr", "bigshott", "qb")
	c := createCoach("jl", "hchg")
	c2 := createCoach("c", "2")
	c2.SetSalary(50000)
	c2.Pay()
	c2.Fine(100)
	fmt.Println(c2.AccountBalance, "Accont balance........")
	man := createManager("mb", "lj")
	man2 := createManager("opul", "nash")
	o.Sign(man)
	o2.Sign(man2)
	man2.Sign(c2)
	man.Sign(c)
	c.Sign(pl)
	c2.Sign(p2)
	man.SetSalary(50000)
	man.Pay()
	fmt.Println("MAKNG REQ NOW")
	c.MakeTradeReq(pl, p2)

	fmt.Println(len(c2.Atti.Requests), "   <----requests")

	man.MediaPost("my life", "man im so awesome!", true)
	fmt.Println("level", man.GetLevel(), "     ")
	ShowPosts(man.League.MessBoard)
	man.Fine(1000)
	fmt.Println("balance should be 4000--- ", man.AccountBalance)
	fmt.Println("----manager's coaches------", man.Coaches[0])
	fmt.Println("------about to fire j l -------")
	man.Fire(c, "we dont need you anymore")
	fmt.Println("----manager's coaches------", len(man.Coaches))
	c2.Sign(p2)
	CutPlayer(c2.Team, p2)
	fmt.Println()
	ShowPosts(man.League.MessBoard)
	//c.MakeTradeReq(pl, p2, false)
	//fmt.Println(" Player:", *pl, pl.Atti.Position, "\n", "Coach:", *c, "\n", "Manager:", *man, "\n", "Owner:", *o, "\n", "Commish:", *com)
	com.MediaPost("nm", "hey wassup yall?", true)
	fmt.Println(c2.Atti.Requests)
	fmt.Println(".......", pl.Team, ".............")
	fmt.Println(pl.GetType())

}
